"""Initial migration

Revision ID: 50970b190540
Revises: 
Create Date: 2026-03-15 15:11:55.351161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50970b190540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('preferred_car', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('cars')
    # ### end Alembic commands ###
